from __future__ import annotations

import datetime
import re
from pathlib import Path


def parse_header(text: str) -> dict:
    lines = text.splitlines()

    title = None
    status = None
    last_updated = None
    canonical = None
    owner = None

    for line in lines[:30]:
        if title is None and line.startswith('# '):
            title = line[2:].strip()

        m = re.match(r'^(Status|Last Updated|Canonical|Owner):\s*(.+?)\s*$', line)
        if not m:
            continue

        key, val = m.group(1), m.group(2)
        if key == 'Status':
            status = val
        elif key == 'Last Updated':
            last_updated = val
        elif key == 'Canonical':
            canonical = val
        elif key == 'Owner':
            owner = val

    return {
        'title': title,
        'status': status,
        'last_updated': last_updated,
        'canonical': canonical,
        'owner': owner,
    }


def main() -> None:
    root = Path('docs')
    rows = []

    for path in sorted(root.rglob('*.md')):
        try:
            text = path.read_text(encoding='utf-8')
        except UnicodeDecodeError:
            text = path.read_bytes().decode('utf-8', errors='replace')

        meta = parse_header(text)
        p = str(path)
        # Treat explicit "Status: Archived" as archive-tier, even if the file lives under `docs/`.
        # This prevents legacy redirect stubs from showing up as "active" docs in reports.
        tier = 'archive' if ('/archive/' in p or '/_archive/' in p or meta.get('status') == 'Archived') else 'active'

        rows.append({
            'path': p,
            **meta,
            'tier': tier,
            'lines': text.count('\n') + 1,
        })

    now = datetime.datetime.utcnow().replace(microsecond=0).isoformat() + 'Z'

    out: list[str] = []
    out.append('# Docs Inventory')
    out.append('Status: Active')
    out.append(f'Last Updated: {now}')
    out.append('Canonical: Yes')
    out.append('Owner: Documentation')
    out.append('')
    out.append('This file is auto-generated by a local script (`scripts/docs_inventory.py`). It lists every `docs/**/*.md` file and its detected header metadata (if present).')
    out.append('')

    active = [r for r in rows if r['tier'] == 'active']
    archive = [r for r in rows if r['tier'] == 'archive']

    def table(rs: list[dict]) -> list[str]:
        t: list[str] = []
        t.append('| Path | Title | Status | Canonical | Owner | Last Updated | Lines |')
        t.append('|---|---|---:|---:|---|---|---:|')
        for r in rs:
            t.append('| {path} | {title} | {status} | {canonical} | {owner} | {last_updated} | {lines} |'.format(
                path=r['path'],
                title=(r['title'] or ''),
                status=(r['status'] or ''),
                canonical=(r['canonical'] or ''),
                owner=(r['owner'] or ''),
                last_updated=(r['last_updated'] or ''),
                lines=r['lines'],
            ))
        t.append('')
        return t

    out.append('## Active Tree (`docs/` excluding archives)')
    out.extend(table(active))

    out.append('## Archives (`docs/archive/**`)')
    out.extend(table(archive))

    Path('docs/_meta/meta-docs-inventory.md').write_text('\n'.join(out) + '\n', encoding='utf-8')
    print('wrote docs/_meta/meta-docs-inventory.md with', len(rows), 'rows')


if __name__ == '__main__':
    main()
